import turtle
turtle.showturtle()
turtle.write("yuange")
turtle.forward(300)
turtle.color("red")
turtle.left(90)
turtle.forward(300)
turtle.goto(0,50)
turtle.goto(0,0)
turtle.penup()
turtle.goto(0,300)
turtle.pendown()
turtle.circle(100)
